name: Deploy Documentation to Pages

on:
  push:
    branches: ["development"]
  workflow_dispatch:
    branches: ["development"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-documentation:
    #if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Vlang
        run: |
          curl "https://raw.githubusercontent.com/freeflowuniverse/herolib/refs/heads/development/install_v.sh" > /tmp/install_v.sh
          bash /tmp/install_v.sh

      - name: Generate documentation
        run: |
          ./doc.vsh
          find .

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "/home/runner/work/herolib/herolib/docs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
